POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "maheshtk",
  "name": "random",
  "password": "random123",
  "gender":   "male",
  "location": "Jaggayyapet"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "maheshtk",
  "password": "random123"
}

###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "maheshtk",
  "oldPassword": "pass123",
  "newPassword": "pas"
}