POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "maheshtalluri",
  "name": "Mahesh Kumar Talluri",
  "password": "mahesh369",
  "gender":   "male",
  "location": "Jaggayyapet"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "maheshtalluri",
  "password": "mahesh159"
}

###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "maheshtalluri",
  "oldPassword": "mahesh753",
  "newPassword": "mahesh159"
}